### ISSUE TITLE
Web app stops

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/dataseer-web#93]
The web app stops after raising this issue. A bit more robustness on the `document` property to avoid an unexpected stop of the application would be necessary I think. 

```
/home/lopez/dataseer-web/routes/backoffice.js:151
        return res.redirect(path.join('../documents', results.successes[0].document.id));
                                                                           ^

TypeError: Cannot read property 'document' of undefined
    at /home/lopez/dataseer-web/routes/backoffice.js:151:76
    at wrapper (/home/lopez/dataseer-web/node_modules/async/dist/async.js:273:20)
    at iteratorCallback (/home/lopez/dataseer-web/node_modules/async/dist/async.js:500:17)
    at /home/lopez/dataseer-web/node_modules/async/dist/async.js:326:20
    at /home/lopez/dataseer-web/routes/backoffice.js:129:16
    at /home/lopez/dataseer-web/lib/upload.js:25:23
    at Request._callback (/home/lopez/dataseer-web/lib/upload.js:58:16)
    at Request.self.callback (/home/lopez/dataseer-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/lopez/dataseer-web/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/lopez/dataseer-web/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by NicolasKieffer** [comment]
Done in commit https://github.com/kermitt2/dataseer-web/commit/70a3f196ee7c0af6ee874906fac73ac0bce0293a

**Comment by kermitt2** [comment]
Thanks !

**Comment by kermitt2** [comment]
mmm I still had the error coming in production after updating the app: 

```
/home/lopez/dataseer-web/routes/backoffice.js:151
        return res.redirect(path.join('../documents', results.successes[0].document.id));
                                                                           ^

TypeError: Cannot read property 'document' of undefined
    at /home/lopez/dataseer-web/routes/backoffice.js:151:76
    at wrapper (/home/lopez/dataseer-web/node_modules/async/dist/async.js:273:20)
    at iteratorCallback (/home/lopez/dataseer-web/node_modules/async/dist/async.js:500:17)
    at /home/lopez/dataseer-web/node_modules/async/dist/async.js:326:20
    at /home/lopez/dataseer-web/routes/backoffice.js:129:16
    at /home/lopez/dataseer-web/lib/upload.js:25:23
...
```

Is there a reason why the fix is not merged?

**Comment by NicolasKieffer** [comment]
PR was created but not merged. Don't know why.
Merge done now.

**Comment by kermitt2** [comment]
Cool, thanks !
